language: cpp

os:
  - linux
  - osx

branches:
  only:
    - master
    - test

addons:
  apt:
    packages: &common_packages
      - libglew-dev
      - libglfw3-dev
      - lcov
      - cmake
      - make
      - gdb

env:
  jobs:
    - BOGUS_JOB=true

jobs:
  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      dist: xenial
      env: USE_COVERAGE=no CC=gcc-9 CXX=g++-9 CXXFLAGS="-std=c++2a -O2 -g"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-9
    - os: linux
      dist: xenial
      env: USE_COVERAGE=yes CC=gcc-9 CXX=g++-9 CXXFLAGS="-std=c++2a -ggdb3 -O0 --coverage -fprofile-arcs -ftest-coverage"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-9
    - os: linux
      dist: xenial
      env: USE_COVERAGE=no CC=clang-9 CXX=clang++-9 CXXFLAGS="-stdlib=libc++ -std=c++2a -O2 -g"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
    - os: osx
      osx_image: xcode11.2
      env: USE_COVERAGE=no CC=clang CXX=clang++ CXXFLAGS="-std=c++2a -O2 -g"

install:
  - cd ..
  - cd irritator
  - mkdir build
  - cd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_COLOR_MAKEFILE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None ..

script:
  - make
  - sudo make install
  - ctest

after_success:
  - if [[ "$USE_COVERAGE" == "yes" ]]; then cd ${TRAVIS_BUILD_DIR} ; fi
  - if [[ "$USE_COVERAGE" == "yes" ]]; then lcov --directory . --capture --output-file coverage.info ; fi
  - if [[ "$USE_COVERAGE" == "yes" ]]; then lcov --remove coverage.info '/usr/*' --output-file coverage.info ; fi
  - if [[ "$USE_COVERAGE" == "yes" ]]; then lcov --remove coverage.info 'external/*' --output-file coverage.info ; fi
  - if [[ "$USE_COVERAGE" == "yes" ]]; then lcov --list coverage.info ; fi
  - if [[ "$USE_COVERAGE" == "yes" ]]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  email:
    on_success: always
