language: cpp

os:
  - linux
  - osx

branches:
  only:
    - master
    - test

addons:
  apt:
    packages: &common_packages
      - lcov
      - cmake
      - make
      - gdb

env:
  jobs:
    - BOGUS_JOB=true

jobs:
  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      dist: xenial
      env: CXX_COMPILER=g++-9 CXX_FLAGS=-std=c++2a
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-9
    - os: linux
      dist: xenial
      env: CXX_COMPILER="clang++-9 -stdlib=libc++" CXX_FLAGS=-std=c++2a
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - clang-9
            - libc++-9-dev
    - os: osx
      osx_image: xcode11.2
      env: CXX_COMPILER=clang++ CXX_FLAGS=c++2a

install:
  - cd ..
  - cd irritator
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CXXFLAGS="$CXX_FLAGS" cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_COLOR_MAKEFILE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug .. ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then CXXFLAGS="$CXX_FLAGS" -g -O0 --coverage -fprofile-arcs -ftest-coverage" cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_COLOR_MAKEFILE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None .. ; fi

script:
  - make
  - sudo make install
  - ctest

after_success:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then cd ${TRAVIS_BUILD_DIR} ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --directory . --capture --output-file coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --remove coverage.info '/usr/*' --output-file coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --remove coverage.info 'external/*' --output-file coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --list coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  email:
    on_success: always
